CREATE TABLE `train_identity` (
  `TransactionID` bigint(20) NOT NULL,
  `id_01` double DEFAULT NULL,
  `id_02` double DEFAULT NULL,
  `id_03` double DEFAULT NULL,
  `id_04` double DEFAULT NULL,
  `id_05` double DEFAULT NULL,
  `id_06` double DEFAULT NULL,
  `id_07` double DEFAULT NULL,
  `id_08` double DEFAULT NULL,
  `id_09` double DEFAULT NULL,
  `id_10` double DEFAULT NULL,
  `id_11` double DEFAULT NULL,
  `id_12` text,
  `id_13` double DEFAULT NULL,
  `id_14` double DEFAULT NULL,
  `id_15` text,
  `id_16` text,
  `id_17` double DEFAULT NULL,
  `id_18` double DEFAULT NULL,
  `id_19` double DEFAULT NULL,
  `id_20` double DEFAULT NULL,
  `id_21` double DEFAULT NULL,
  `id_22` double DEFAULT NULL,
  `id_23` text,
  `id_24` double DEFAULT NULL,
  `id_25` double DEFAULT NULL,
  `id_26` double DEFAULT NULL,
  `id_27` text,
  `id_28` text,
  `id_29` text,
  `id_30` text,
  `id_31` text,
  `id_32` double DEFAULT NULL,
  `id_33` text,
  `id_34` text,
  `id_35` text,
  `id_36` text,
  `id_37` text,
  `id_38` text,
  `DeviceType` text,
  `DeviceInfo` text,
  PRIMARY KEY (`TransactionID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `train_transaction` (
  `TransactionID` bigint(20) NOT NULL,
  `isFraud` bigint(20) DEFAULT NULL,
  `TransactionDT` bigint(20) DEFAULT NULL,
  `TransactionAmt` double DEFAULT NULL,
  `ProductCD` text,
  `card1` bigint(20) DEFAULT NULL,
  `card2` double DEFAULT NULL,
  `card3` double DEFAULT NULL,
  `card4` text,
  `card5` double DEFAULT NULL,
  `card6` text,
  `addr1` double DEFAULT NULL,
  `addr2` double DEFAULT NULL,
  `dist1` double DEFAULT NULL,
  `dist2` double DEFAULT NULL,
  `P_emaildomain` text,
  `R_emaildomain` text,
  `C1` double DEFAULT NULL,
  `C2` double DEFAULT NULL,
  `C3` double DEFAULT NULL,
  `C4` double DEFAULT NULL,
  `C5` double DEFAULT NULL,
  `C6` double DEFAULT NULL,
  `C7` double DEFAULT NULL,
  `C8` double DEFAULT NULL,
  `C9` double DEFAULT NULL,
  `C10` double DEFAULT NULL,
  `C11` double DEFAULT NULL,
  `C12` double DEFAULT NULL,
  `C13` double DEFAULT NULL,
  `C14` double DEFAULT NULL,
  `D1` double DEFAULT NULL,
  `D2` double DEFAULT NULL,
  `D3` double DEFAULT NULL,
  `D4` double DEFAULT NULL,
  `D5` double DEFAULT NULL,
  `D6` double DEFAULT NULL,
  `D7` double DEFAULT NULL,
  `D8` double DEFAULT NULL,
  `D9` double DEFAULT NULL,
  `D10` double DEFAULT NULL,
  `D11` double DEFAULT NULL,
  `D12` double DEFAULT NULL,
  `D13` double DEFAULT NULL,
  `D14` double DEFAULT NULL,
  `D15` double DEFAULT NULL,
  `M1` text,
  `M2` text,
  `M3` text,
  `M4` text,
  `M5` text,
  `M6` text,
  `M7` text,
  `M8` text,
  `M9` text,
  `V1` double DEFAULT NULL,
  `V2` double DEFAULT NULL,
  `V3` double DEFAULT NULL,
  `V4` double DEFAULT NULL,
  `V5` double DEFAULT NULL,
  `V6` double DEFAULT NULL,
  `V7` double DEFAULT NULL,
  `V8` double DEFAULT NULL,
  `V9` double DEFAULT NULL,
  `V10` double DEFAULT NULL,
  `V11` double DEFAULT NULL,
  `V12` double DEFAULT NULL,
  `V13` double DEFAULT NULL,
  `V14` double DEFAULT NULL,
  `V15` double DEFAULT NULL,
  `V16` double DEFAULT NULL,
  `V17` double DEFAULT NULL,
  `V18` double DEFAULT NULL,
  `V19` double DEFAULT NULL,
  `V20` double DEFAULT NULL,
  `V21` double DEFAULT NULL,
  `V22` double DEFAULT NULL,
  `V23` double DEFAULT NULL,
  `V24` double DEFAULT NULL,
  `V25` double DEFAULT NULL,
  `V26` double DEFAULT NULL,
  `V27` double DEFAULT NULL,
  `V28` double DEFAULT NULL,
  `V29` double DEFAULT NULL,
  `V30` double DEFAULT NULL,
  `V31` double DEFAULT NULL,
  `V32` double DEFAULT NULL,
  `V33` double DEFAULT NULL,
  `V34` double DEFAULT NULL,
  `V35` double DEFAULT NULL,
  `V36` double DEFAULT NULL,
  `V37` double DEFAULT NULL,
  `V38` double DEFAULT NULL,
  `V39` double DEFAULT NULL,
  `V40` double DEFAULT NULL,
  `V41` double DEFAULT NULL,
  `V42` double DEFAULT NULL,
  `V43` double DEFAULT NULL,
  `V44` double DEFAULT NULL,
  `V45` double DEFAULT NULL,
  `V46` double DEFAULT NULL,
  `V47` double DEFAULT NULL,
  `V48` double DEFAULT NULL,
  `V49` double DEFAULT NULL,
  `V50` double DEFAULT NULL,
  `V51` double DEFAULT NULL,
  `V52` double DEFAULT NULL,
  `V53` double DEFAULT NULL,
  `V54` double DEFAULT NULL,
  `V55` double DEFAULT NULL,
  `V56` double DEFAULT NULL,
  `V57` double DEFAULT NULL,
  `V58` double DEFAULT NULL,
  `V59` double DEFAULT NULL,
  `V60` double DEFAULT NULL,
  `V61` double DEFAULT NULL,
  `V62` double DEFAULT NULL,
  `V63` double DEFAULT NULL,
  `V64` double DEFAULT NULL,
  `V65` double DEFAULT NULL,
  `V66` double DEFAULT NULL,
  `V67` double DEFAULT NULL,
  `V68` double DEFAULT NULL,
  `V69` double DEFAULT NULL,
  `V70` double DEFAULT NULL,
  `V71` double DEFAULT NULL,
  `V72` double DEFAULT NULL,
  `V73` double DEFAULT NULL,
  `V74` double DEFAULT NULL,
  `V75` double DEFAULT NULL,
  `V76` double DEFAULT NULL,
  `V77` double DEFAULT NULL,
  `V78` double DEFAULT NULL,
  `V79` double DEFAULT NULL,
  `V80` double DEFAULT NULL,
  `V81` double DEFAULT NULL,
  `V82` double DEFAULT NULL,
  `V83` double DEFAULT NULL,
  `V84` double DEFAULT NULL,
  `V85` double DEFAULT NULL,
  `V86` double DEFAULT NULL,
  `V87` double DEFAULT NULL,
  `V88` double DEFAULT NULL,
  `V89` double DEFAULT NULL,
  `V90` double DEFAULT NULL,
  `V91` double DEFAULT NULL,
  `V92` double DEFAULT NULL,
  `V93` double DEFAULT NULL,
  `V94` double DEFAULT NULL,
  `V95` double DEFAULT NULL,
  `V96` double DEFAULT NULL,
  `V97` double DEFAULT NULL,
  `V98` double DEFAULT NULL,
  `V99` double DEFAULT NULL,
  `V100` double DEFAULT NULL,
  `V101` double DEFAULT NULL,
  `V102` double DEFAULT NULL,
  `V103` double DEFAULT NULL,
  `V104` double DEFAULT NULL,
  `V105` double DEFAULT NULL,
  `V106` double DEFAULT NULL,
  `V107` double DEFAULT NULL,
  `V108` double DEFAULT NULL,
  `V109` double DEFAULT NULL,
  `V110` double DEFAULT NULL,
  `V111` double DEFAULT NULL,
  `V112` double DEFAULT NULL,
  `V113` double DEFAULT NULL,
  `V114` double DEFAULT NULL,
  `V115` double DEFAULT NULL,
  `V116` double DEFAULT NULL,
  `V117` double DEFAULT NULL,
  `V118` double DEFAULT NULL,
  `V119` double DEFAULT NULL,
  `V120` double DEFAULT NULL,
  `V121` double DEFAULT NULL,
  `V122` double DEFAULT NULL,
  `V123` double DEFAULT NULL,
  `V124` double DEFAULT NULL,
  `V125` double DEFAULT NULL,
  `V126` double DEFAULT NULL,
  `V127` double DEFAULT NULL,
  `V128` double DEFAULT NULL,
  `V129` double DEFAULT NULL,
  `V130` double DEFAULT NULL,
  `V131` double DEFAULT NULL,
  `V132` double DEFAULT NULL,
  `V133` double DEFAULT NULL,
  `V134` double DEFAULT NULL,
  `V135` double DEFAULT NULL,
  `V136` double DEFAULT NULL,
  `V137` double DEFAULT NULL,
  `V138` double DEFAULT NULL,
  `V139` double DEFAULT NULL,
  `V140` double DEFAULT NULL,
  `V141` double DEFAULT NULL,
  `V142` double DEFAULT NULL,
  `V143` double DEFAULT NULL,
  `V144` double DEFAULT NULL,
  `V145` double DEFAULT NULL,
  `V146` double DEFAULT NULL,
  `V147` double DEFAULT NULL,
  `V148` double DEFAULT NULL,
  `V149` double DEFAULT NULL,
  `V150` double DEFAULT NULL,
  `V151` double DEFAULT NULL,
  `V152` double DEFAULT NULL,
  `V153` double DEFAULT NULL,
  `V154` double DEFAULT NULL,
  `V155` double DEFAULT NULL,
  `V156` double DEFAULT NULL,
  `V157` double DEFAULT NULL,
  `V158` double DEFAULT NULL,
  `V159` double DEFAULT NULL,
  `V160` double DEFAULT NULL,
  `V161` double DEFAULT NULL,
  `V162` double DEFAULT NULL,
  `V163` double DEFAULT NULL,
  `V164` double DEFAULT NULL,
  `V165` double DEFAULT NULL,
  `V166` double DEFAULT NULL,
  `V167` double DEFAULT NULL,
  `V168` double DEFAULT NULL,
  `V169` double DEFAULT NULL,
  `V170` double DEFAULT NULL,
  `V171` double DEFAULT NULL,
  `V172` double DEFAULT NULL,
  `V173` double DEFAULT NULL,
  `V174` double DEFAULT NULL,
  `V175` double DEFAULT NULL,
  `V176` double DEFAULT NULL,
  `V177` double DEFAULT NULL,
  `V178` double DEFAULT NULL,
  `V179` double DEFAULT NULL,
  `V180` double DEFAULT NULL,
  `V181` double DEFAULT NULL,
  `V182` double DEFAULT NULL,
  `V183` double DEFAULT NULL,
  `V184` double DEFAULT NULL,
  `V185` double DEFAULT NULL,
  `V186` double DEFAULT NULL,
  `V187` double DEFAULT NULL,
  `V188` double DEFAULT NULL,
  `V189` double DEFAULT NULL,
  `V190` double DEFAULT NULL,
  `V191` double DEFAULT NULL,
  `V192` double DEFAULT NULL,
  `V193` double DEFAULT NULL,
  `V194` double DEFAULT NULL,
  `V195` double DEFAULT NULL,
  `V196` double DEFAULT NULL,
  `V197` double DEFAULT NULL,
  `V198` double DEFAULT NULL,
  `V199` double DEFAULT NULL,
  `V200` double DEFAULT NULL,
  `V201` double DEFAULT NULL,
  `V202` double DEFAULT NULL,
  `V203` double DEFAULT NULL,
  `V204` double DEFAULT NULL,
  `V205` double DEFAULT NULL,
  `V206` double DEFAULT NULL,
  `V207` double DEFAULT NULL,
  `V208` double DEFAULT NULL,
  `V209` double DEFAULT NULL,
  `V210` double DEFAULT NULL,
  `V211` double DEFAULT NULL,
  `V212` double DEFAULT NULL,
  `V213` double DEFAULT NULL,
  `V214` double DEFAULT NULL,
  `V215` double DEFAULT NULL,
  `V216` double DEFAULT NULL,
  `V217` double DEFAULT NULL,
  `V218` double DEFAULT NULL,
  `V219` double DEFAULT NULL,
  `V220` double DEFAULT NULL,
  `V221` double DEFAULT NULL,
  `V222` double DEFAULT NULL,
  `V223` double DEFAULT NULL,
  `V224` double DEFAULT NULL,
  `V225` double DEFAULT NULL,
  `V226` double DEFAULT NULL,
  `V227` double DEFAULT NULL,
  `V228` double DEFAULT NULL,
  `V229` double DEFAULT NULL,
  `V230` double DEFAULT NULL,
  `V231` double DEFAULT NULL,
  `V232` double DEFAULT NULL,
  `V233` double DEFAULT NULL,
  `V234` double DEFAULT NULL,
  `V235` double DEFAULT NULL,
  `V236` double DEFAULT NULL,
  `V237` double DEFAULT NULL,
  `V238` double DEFAULT NULL,
  `V239` double DEFAULT NULL,
  `V240` double DEFAULT NULL,
  `V241` double DEFAULT NULL,
  `V242` double DEFAULT NULL,
  `V243` double DEFAULT NULL,
  `V244` double DEFAULT NULL,
  `V245` double DEFAULT NULL,
  `V246` double DEFAULT NULL,
  `V247` double DEFAULT NULL,
  `V248` double DEFAULT NULL,
  `V249` double DEFAULT NULL,
  `V250` double DEFAULT NULL,
  `V251` double DEFAULT NULL,
  `V252` double DEFAULT NULL,
  `V253` double DEFAULT NULL,
  `V254` double DEFAULT NULL,
  `V255` double DEFAULT NULL,
  `V256` double DEFAULT NULL,
  `V257` double DEFAULT NULL,
  `V258` double DEFAULT NULL,
  `V259` double DEFAULT NULL,
  `V260` double DEFAULT NULL,
  `V261` double DEFAULT NULL,
  `V262` double DEFAULT NULL,
  `V263` double DEFAULT NULL,
  `V264` double DEFAULT NULL,
  `V265` double DEFAULT NULL,
  `V266` double DEFAULT NULL,
  `V267` double DEFAULT NULL,
  `V268` double DEFAULT NULL,
  `V269` double DEFAULT NULL,
  `V270` double DEFAULT NULL,
  `V271` double DEFAULT NULL,
  `V272` double DEFAULT NULL,
  `V273` double DEFAULT NULL,
  `V274` double DEFAULT NULL,
  `V275` double DEFAULT NULL,
  `V276` double DEFAULT NULL,
  `V277` double DEFAULT NULL,
  `V278` double DEFAULT NULL,
  `V279` double DEFAULT NULL,
  `V280` double DEFAULT NULL,
  `V281` double DEFAULT NULL,
  `V282` double DEFAULT NULL,
  `V283` double DEFAULT NULL,
  `V284` double DEFAULT NULL,
  `V285` double DEFAULT NULL,
  `V286` double DEFAULT NULL,
  `V287` double DEFAULT NULL,
  `V288` double DEFAULT NULL,
  `V289` double DEFAULT NULL,
  `V290` double DEFAULT NULL,
  `V291` double DEFAULT NULL,
  `V292` double DEFAULT NULL,
  `V293` double DEFAULT NULL,
  `V294` double DEFAULT NULL,
  `V295` double DEFAULT NULL,
  `V296` double DEFAULT NULL,
  `V297` double DEFAULT NULL,
  `V298` double DEFAULT NULL,
  `V299` double DEFAULT NULL,
  `V300` double DEFAULT NULL,
  `V301` double DEFAULT NULL,
  `V302` double DEFAULT NULL,
  `V303` double DEFAULT NULL,
  `V304` double DEFAULT NULL,
  `V305` double DEFAULT NULL,
  `V306` double DEFAULT NULL,
  `V307` double DEFAULT NULL,
  `V308` double DEFAULT NULL,
  `V309` double DEFAULT NULL,
  `V310` double DEFAULT NULL,
  `V311` double DEFAULT NULL,
  `V312` double DEFAULT NULL,
  `V313` double DEFAULT NULL,
  `V314` double DEFAULT NULL,
  `V315` double DEFAULT NULL,
  `V316` double DEFAULT NULL,
  `V317` double DEFAULT NULL,
  `V318` double DEFAULT NULL,
  `V319` double DEFAULT NULL,
  `V320` double DEFAULT NULL,
  `V321` double DEFAULT NULL,
  `V322` double DEFAULT NULL,
  `V323` double DEFAULT NULL,
  `V324` double DEFAULT NULL,
  `V325` double DEFAULT NULL,
  `V326` double DEFAULT NULL,
  `V327` double DEFAULT NULL,
  `V328` double DEFAULT NULL,
  `V329` double DEFAULT NULL,
  `V330` double DEFAULT NULL,
  `V331` double DEFAULT NULL,
  `V332` double DEFAULT NULL,
  `V333` double DEFAULT NULL,
  `V334` double DEFAULT NULL,
  `V335` double DEFAULT NULL,
  `V336` double DEFAULT NULL,
  `V337` double DEFAULT NULL,
  `V338` double DEFAULT NULL,
  `V339` double DEFAULT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX ('TransactionDT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE `train_transaction`;
CREATE TABLE `train_transaction` (
  `TransactionID` bigint(20) NOT NULL,
  `isFraud` bigint(20) DEFAULT NULL,
  `TransactionDT` bigint(20) DEFAULT NULL,
  `TransactionAmt` double DEFAULT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX ('TransactionDT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `test_transaction`;
CREATE TABLE `test_transaction` (
  `TransactionID` bigint(20) NOT NULL,
  `isFraud` bigint(20) DEFAULT NULL,
  `TransactionDT` bigint(20),
  `TransactionAmt` double DEFAULT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX(`TransactionDT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


USE fraud;
ALTER TABLE `test_transaction`
MODIFY COLUMN `TransactionID` bigint(20) NOT NULL FIRST,
ADD PRIMARY KEY (`TransactionID`),
MODIFY COLUMN `TransactionDT` bigint(20) NOT NULL,
ADD INDEX (`TransactionID`);

show indexes from test_transaction

USE fraud;
SELECT
    total,
    cnt_d9,
    ( cnt_d9 / total ) AS ratio
FROM(
    SELECT
        count( TransactionID ) AS total,
        count( D9 ) AS cnt_d9
    FROM
        train_transaction
    WHERE
    {where}
) AS foo

